server:
  port: 8080
  shutdown: graceful
application:
  context-path: /catalogo-marketplace/api
spring:
  application:
    name: catalogo-marketplace
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/
      database: admin
  profiles:
    active: local
management:
  health:
    livenessstate.enabled: true
    readinessstate.enabled: true
  endpoints:
    web:
      exposure:
        include: health, shutdown
  endpoint:
    shutdown:
      enabled: true
    health:
      probes.enabled: true
cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    credentials:
      access-key: ANUJDEKAVADIYAEXAMPLE
      secret-key: 2QvM4/Tdmf38SkcD/qalvXO4EXAMPLEKEY
    end-point:
      uri: http://localhost:4566